SmartCondWeb/Areas/Admin/Controllers/UnitController.cs
using Microsoft.AspNetCore.Mvc;
using SmartCondWeb.DataAcess.Persist.Interfaces;
using SmartCondWeb.Models;
using SmartCondWeb.Domain.Utils;
namespace SmartCondWeb.Areas.Admin.Controllers;
[Area("Admin")]
public class UnitController : Controller
{
    private readonly IUnitPersist persist;
    private readonly IWebHostEnvironment webHostEnvironment;


    public UnitController(IUnitPersist persist, IWebHostEnvironment webHostEnvironment)
    {
        this.persist = persist;
        this.webHostEnvironment = webHostEnvironment;
    }
    public IActionResult Index()
    {
        try
        {
            var units = persist.GetAllUnits();
            return View(units);
        }
        catch (Exception ex)
        {
            return RedirectToAction("Error","Shared");
        }
        
    }
    public IActionResult UnitReport()
    {
        var units = persist.GetAllUnits();
        string wwwRootPath = webHostEnvironment.WebRootPath;
        CreateReportUnits createReport = new CreateReportUnits(wwwRootPath);
        var path = createReport.ReportPDF(units);
        if (!System.IO.File.Exists(path)) 
        { 
            return NotFound("O arquivo não foi encontrado!");
        }
        byte[] fileByte = System.IO.File.ReadAllBytes(path);
        return File(fileByte, "application/pdf", "Relatório_Das_Unidades.pdf");
    }
}

SmartCondWeb/Areas/Admin/Controllers/VehicleController.cs
using Microsoft.AspNetCore.Mvc;
using SmartCondWeb.DataAcess.Persist.Interfaces;
using SmartCondWeb.Domain.Things;
using SmartCondWeb.Domain.Utils;

namespace SmartCondWeb.Areas.Admin.Controllers;
[Area("Admin")]
public class VehicleController : Controller
{
    private readonly IUnitPersist unitPersist;
    private readonly IVehiclePersist vehiclePersist;
    private readonly IWebHostEnvironment webHostEnvironment;

    public VehicleController(IUnitPersist unitPersist, IVehiclePersist vehiclePersist, IWebHostEnvironment webHostEnvironment)
    {
        this.unitPersist = unitPersist;
        this.vehiclePersist = vehiclePersist;
        this.webHostEnvironment = webHostEnvironment;
    }
    public IActionResult Index()
    {
        var vehicles = vehiclePersist.GetAllVehicles();
        return View(vehicles);
    }
    public IActionResult Add(int id)
    {
        try
        {
            Vehicle vehicle = new Vehicle();
            vehicle.UnitId = id;
            return View(vehicle);
        }
        catch (Exception ex) 
        {
            return RedirectToAction("Error", "Shared");
        }
        
    }
    [HttpPost]
    public IActionResult Add(Vehicle vehicle)
    {
        try
        {
            vehicle.Id = 0;
            vehiclePersist.Add(vehicle);
            vehiclePersist.SaveChange();
            return RedirectToAction("Index", "Unit");
        }
        catch (Exception ex) 
        {
            return RedirectToAction("Error", "Shared");
        }
    }

    public IActionResult Update(int  id) 
    {
        try
        {
            var vehicle = vehiclePersist.GetVehicleForId(id);
            return View(vehicle);
        }
        catch (Exception ex) 
        {
            return RedirectToAction("Error", "Shared");
        }
    }
    [HttpPost]
    public IActionResult Update(Vehicle vehicle) 
    {
        try
        {
            vehiclePersist.Update(vehicle);
            vehiclePersist.SaveChange();
            return RedirectToAction("Index", "Unit");
        }
        catch(Exception ex) 
        {
            return RedirectToAction("Error", "Shared");
        }
    }

    public IActionResult Delete(int id)
    {
        try
        {
            Vehicle vehicle = vehiclePersist.GetVehicleForId(id);
            vehiclePersist.Delete(vehicle);
            vehiclePersist.SaveChange();
            return RedirectToAction("Index", "Unit");
        }
        catch (Exception ex)
        {
            return RedirectToAction("Error", "Shared");
        }
    }
    public IActionResult ReportVehicle()
    {
        var vehicles = vehiclePersist.GetAllVehicles();
        vehicles = vehicles.OrderBy(v => v.Unit.UnitCode).ToList();
        string wwwRootPath = webHostEnvironment.WebRootPath;
        CreateReportVehicles createReport = new CreateReportVehicles(wwwRootPath);
        var path = createReport.ReportPDF(vehicles);
        if (!System.IO.File.Exists(path))
        {
            return NotFound("O arquivo não foi encontrado!");
        }
        byte[] fileByte = System.IO.File.ReadAllBytes(path);
        return File(fileByte, "application/pdf", "Relatorio_De_Veiculos.pdf");
    }
}

SmartCondWeb/Areas/User/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Projeto Engenharia Software V</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SmartCondWeb.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand">
                    <img src="/images/logo/logo.png" alt="" width="75" height="75">
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                       
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Portaria
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" asp-area="Admin" asp-controller="Resident" asp-action="Index">Lista De Moradores</a></li>
                                <li><a class="dropdown-item" asp-area="Admin" asp-controller="VisitorAccess" asp-action="Index">Controle De Acesso</a></li>
                                <li><a class="dropdown-item" asp-area="Admin" asp-controller="" asp-action="">Relatório Da Portaria</a></li>
                                <li><a class="dropdown-item" asp-area="Admin" asp-controller="" asp-action="">Gerar Relatório</a></li>
                            </ul>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Administrativo
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" asp-area="Admin" asp-controller="Unit" asp-action="Index" >Unidades</a></li>
                                <li><a class="dropdown-item" asp-area="Admin" asp-controller="Homeowner" asp-action="Index" >Proprietários</a></li>
                                <li><a class="dropdown-item" asp-area="Admin" asp-controller="Vehicle" asp-action="Index" >Veículos</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Projeto Engenharia Software V - Felipe Fernandes Soares - Universidade Cruzeiro do Sul.
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

SmartCondWeb/Areas/User/Views/Shared/_Notification.cshtml
@if(TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
    </script>
    
}
@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]');
    </script>
}